FROM mwader/static-ffmpeg:latest AS ffmpeg

FROM filebrowser/filebrowser:latest

COPY --from=ffmpeg /ffmpeg /usr/local/bin/ffmpeg
COPY --from=ffmpeg /ffprobe /usr/local/bin/ffprobe

COPY --chown=1000:1000 config/.filebrowser.json /defaults/settings.json
